### ISSUE TITLE
4주차) Controller

### ISSUE THREAD

**Issue by juhwanHeo** [juhwanHeo/study-k8s#47]
> PR Title은 `study 주차구분 / 내용 / 각자이름`으로 올려주시고, 
ex) Week4/ Controller
Branch naming은 `week3/{각자이름}` 입니다.
ex) week4/juhwan

> 이번 과제의 Reviewer분들은 박수정, 최대준, 김상진 3분 + 허주환 or 이주원 총 4명입니다.

### 과제 1) ReplicaSet으로 replication factor 3 인 board Pod를 만들어주세요.
> 이미지 `image: gjwnghks99/board:1.0.0`를 사용
- 제출
  - Path: week4/`{각자이름}`/board-replication.yaml 

### 과제 2) Deployment를 이용하여, Rolling Update 진행해 주세요.
> 이미지 `image: gjwnghks99/board:1.0.0`를 `image: gjwnghks99/board:1.0.1`로 Rolling Update한 Record 기록을 첨부해 주세요
- 제출
  - Path: week4/`{각자이름}`/rolling-update-deployment.yaml 
  - 해당 과제는 Rolling Update를 실행한 내역의 image를 꼭 첨부해 주세요.

### 과제 3) CronJob으로 매 3분마다 실행되도록 만들어주세요.
>`image: gjwnghks99/board:1.0.0`
실행 예시 )
3, 6, 9, 12, 15, ... 3 * n 
0시 0분에 시작 --> 0시 3분, 0시 6분, ..., N시 0 + 3*n

- 제출
  - Path: week4/`{각자이름}`/cronjob-board.yaml 

## 다음주차 강의
> 10월은 ... 다시 2번의 스터디가 있을 예정입니다.

### 발표자: 이주원
- [7-1 쿠버네티스 Service 개념과 종류!](https://youtu.be/5sKkIg7k8nw?feature=shared)
- [7-2 (서비스 1 ~ 2). 쿠버네티스 Service 4가지 종류 실습해보기](https://youtu.be/WaJyY5KvZj8?feature=shared)

### 발표자: 우시영
- [7-2 (서비스 3 ~ 4). 쿠버네티스 Service 4가지 종류 실습해보기](https://youtu.be/WaJyY5KvZj8?feature=shared)
- [7-3. 쿠버네티스 Headless Service와 Kube Proxy 강좌](https://youtu.be/ilQSgu8qt0o?feature=shared)

### 추가 안내사항
- [발표순서](https://juhwanheo.notion.site/Kubernetes-b769d0d3c120485fad124559cda80bcd?pvs=4)
- Convention message 연습안내
  - https://velog.io/@archivvonjang/Git-Commit-Message-Convention
  - https://doublesprogramming.tistory.com/256

**Comment by sangjin0521** [comment]
@juhwanHeo Branch naming은 week3/{각자이름} 입니다에 오타가 있습니다! week4입니다
